ZapConfig:
  Filename: "zap.log"
  MaxSize: 5
  MaxAge: 30
  MaxBackups: 1000

DatabaseConfig:
  MysqlConfig:
    Username: "root"
    Password: "123456"
    Addr: "mysql:3306"
    DB: "chatroom"
  RedisConfig:
    Addr: "redis:6379"
    Password: ""
    DB: 0
